### ISSUE TITLE
Possible to tag a release?

### ISSUE THREAD

**Issue by Pton** [artisansdk/ratelimiter#2]
Hey, we really enjoy using your library for ratelimiting in Larvel. However a small issue we encounter is that this package does not have any tagged releases, thus `dev-master` is required in our composer.json. This is bad practice and it's prefered to use [semver](https://semver.org/) instead. That way no backwards incompatible changes should be made when only updating minor versions. How do you feel about this? Would it be possible for this package to adhere to semver standards?

**Comment by dalabarge** [comment]
Yes, we will be tagging with semver. You can expect a `1.0.0` tag to drop by end of summer for sure, and maybe sooner if I feel that our version 1 API is stable enough to commit to semver going forward. 

Thanks for using the package! Let me know if you have any issues with it.

**Comment by Pton** [comment]
That's good to hear, thank you for letting me know! 😄

**Comment by telkins** [comment]
Any movement here...?  Asking for a friend.  😅

**Comment by dalabarge** [comment]
Tagged `1.0.0-rc1` which is L5 and PHP 7 compatible as `dev-master` was. I'm looking at updating to be L5-8 compatible with PHP 7-8 as well and will tag that as `1.0.0`.

**Comment by dalabarge** [comment]
Tagged `1.0.0-rc2` which is L6-8 and PHP 8 compatible as far as I tests go. I'm looking for feedback on integration so please post any issues with compatibility and preferably pull requests for any fixes for anything that breaks when upgrading with newer versions of Laravel. I'll stable release then once I'm further convinced.
